apiVersion: v1
kind: ingress
metadata:
  name: frontend-ingress
spec:
  rules:
  - host: saay.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: front-clusterIP-service
            port:
              number: 3000

